name: "Bump Action"

on:
  workflow_call:
    outputs:
        new_tag:
          description: "Le nouveau tag généré"
          value: ${{ jobs.bump.outputs.tag_output }}
        changelog:
          description: "Le changelog généré"
          value: ${{ jobs.bump.outputs.changelog_output }}

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      tag_output: ${{ steps.tag.outputs.new_tag }}
      changelog_output: ${{ steps.tag.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump tag version
        id: tag
        uses: ValoriaTechnologia/github-tag-action@v0.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: false
          commit_analyser_preset: conventionalcommits

      
